config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "task/:id", to: "tasks#show", as: :task

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "task/:id", to: "tasks#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for (@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

<%link_to "Go to Task", tasks_path %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
  <%= link_to "Create Task", tasks_new_path %>

<% @tasks.each do |task| %>
  <p> <%= task.title %></p>
  <p> <%= task.details %></p>
  <p> <%= task.completed %></p>
  <%= link_to "Go to Task", task_path(task) %>
  <%= link_to "Edit Task", edit_path(task) %>

  <hr>
<% end %>

app/views/tasks/new.html.erb
<%= render "form" %>

<%link_to "Go to Task", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

  <p> <%= @task.details %></p>
  <p> <%= @task.completed %></p>

<%= link_to "Back to all Tasks", tasks_path %>